name: "task1"
source:
  host: "sftp.source1.com"
  port: 22
  username: "user1"
  password: "pass1"
target:
  host: "sftp.target1.com"
  port: 22
  username: "user1"
  privateKeyPath: "/path/to/key1.pem"
sourcePath: "/remote/source/file1.csv"
sourceFormat: "csv"
targetPath: "/remote/target/file1.json"
targetFormat: "json"
templateName: "csv-to-json.ftl"
