name: "task1"
source:
  host: "192.168.1.100"
  port: 2223
  username: "sftp-demo"
  password: "Hello.123"
target:
  host: "192.168.1.100"
  port: 2223
  username: "sftp-demo"
  password: "Hello.123"
sourcePath: "demo/source/test.csv"
sourceFormat: "csv"
targetPath: "demo/target/test.json"
targetFormat: "json"
templateName: "csv-to-json.ftl"
